all:				Server.class Client.class

Server.class:			Server.java
				@javac Server.java

Client.class:			Client.java
				@javac Client.java

clean:
				@rm -rf *.class *~

info:
				@echo "(c) Bruno Costa (21 mar. 2019)"
